### ISSUE TITLE
CLARIN Latvian metadata

### ISSUE THREAD

**Issue by arnivoit** [clarin-eric/SPF-SPs-metadata#168]
According to QA report, CLARIN Latvian metadata (https://repository.clarin.lv/shibboleth) is fixed. Would it be possible to consider readding it to _production_ branch?

**Comment by andmor-** [comment]
It's almost good. Please check https://github.com/clarin-eric/SPF-SPs-metadata/pull/166#issuecomment-577617715

**Comment by arnivoit** [comment]
Fixed PrivacyStatementURL and created a pull request.

**Comment by andmor-** [comment]
Technically everything is now ready. We just need CLARIN Latvia to fill in the [centre registration form](https://www.clarin.eu/webform/registration-form-centre-registry) for the centre hosting this service provider.

**Comment by andmor-** [comment]
@arnivoit the SP is propagated to eduGAIN and all national federations, still I cannot use IdPs from almost any country but Latvia.
Which metadata providers are you using in your shibboleth2.xml?

**Comment by arnivoit** [comment]
We used two metadata providers:

https://infra.clarin.eu/aai/prod_md_about_clarin_erics_idp.xml and 
https://laife.lanet.lv/metadata/laife-metadata.xml

Now I changed second to https://metadata.eduid.cz/entities/edugain+idp

I hope it resolves this issue.

**Comment by andmor-** [comment]
Yes. Seems to work. However since you are using the [CLARIN central discovery service](https://discovery.clarin.eu/) I would recommend you also use the [CLARIN central metadata feed](https://infra.clarin.eu/aai/prod_md_about_spf_idps.xml) as described in https://www.clarin.eu/node/3314, this will ensure that the IdPs visible in the discovery service will actually be the ones also loaded by the SP. Thus avoiding many situations like this one where the discovery service was showing all IdPs from CLARIN countries but the SP was only reading the Latvian ones.

Alternatively you can use the ["all IdPs in the world feed"](https://infra.clarin.eu/aai/prod_md_about_edugain_idps.xml) and its [corresponding discovery service](https://discovery.clarin.eu/feed/edugain) as described in: https://www.clarin.eu/content/clarin-discovery-service

If you want to use the lindat feed (https://metadata.eduid.cz/entities/edugain+idp) I would recommend you also use their discovery service.

**Comment by arnivoit** [comment]
Thank you, this information was what we needed. I reconfigured the feed 
as recommended, configuring just these two:

  * The aggregated SPF Identity Providers
    <https://infra.clarin.eu/aai/prod_md_about_spf_idps.xml>
  * The CLARIN Identity Provider
    <https://infra.clarin.eu/aai/prod_md_about_clarin_erics_idp.xml>

**Comment by andmor-** [comment]
Nice. I just tested it using the Utrecht University IdP and everything seems to be working.
