### ISSUE TITLE
certificate roll-over metadata update question

### ISSUE THREAD

**Issue by raphywink** [clarin-eric/SPF-SPs-metadata#213]
Dear CLARIN-ERIC/SPF-SPs-metadata Team,

We are currently in the process of performing a certificate roll-over and want to update our metadata accordingly. Unfortunately our own documentation of the process is fairly outdated, so I just wanted to double check that I have understood the process correctly. Do I/we simply place our new `<ds:KeyName>Standby</ds:KeyName>` key into [this](https://github.com/clarin-eric/SPF-SPs-metadata/blob/master/metadata/clarin.phonetik.uni-muenchen.de.xml#L56) location and submit a pull-request? Sorry if this is a stupid question and/or I have missed the information about what exactly we have to do in case of a certificate roll-over. 

Thanks in advance

Greetings from Munich

**Comment by andmor-** [comment]
To do a certificate update without any service disruption you should do the certificate rollover. See [this](https://www.switch.ch/aai/guides/sp/certificate-rollover/) to get a process overview and let us know if you have doubts.

So yes: first you add your key to that location without deleting the old one (instead of step 2 from the linked overview). And then on a later PR you remove the old key (instead of step 4 from the linked overview). The remaining steps should be the same

**Comment by raphywink** [comment]
Awesome! Thanks heaps for the quick reply! That is exactly what we were not quite sure of: 

1. additionally add "Standby" to the already listed "Active" -> PR -> another PR when "Standby" replaces "Active"

vs.

2. simply replace keys -> PR

but then 1. it is :-)
