### ISSUE TITLE
Lack of errors in the QA report indicates either a valid PR or just an old QA report

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/SPF-SPs-metadata#94]
When a PR with no errors is merged, the QA report should be regenerated. But since the QA report only displays the errors there's no way to know if the lack of errors in the QA report indicates a valid PR or if the QA report is just old. Adding a timestamp to the report should be enough.

Alternatively, the readme could specify how long to wait for the report.

**Comment by emanueldima** [comment]
Note: the generation timestamp shows up in the HTTP headers:
> last-modified: Mon, 21 Jan 2019 16:10:19 GMT

**Comment by andmor-** [comment]
yes. This is an old problem. The current idea is to include the time of the generation of the report and commit ID on the report itself. But we did not get around to do it yet.

You can make sure that the report is new, by looking at the Travis state on the PR merge commit. As soon as you have a green arrow, the report you see is be the new one. You can also switch to the `gh-pages` branch and see if the result was already committed by Travis.

Point 7. states to explicitly wait for the Travis build to finish. But it is not clear about how to do that.
I will try to improve the text for the time being.

**Comment by andmor-** [comment]
Also the trac documentation about the workflow should be be improved the same way:
https://trac.clarin.eu/wiki/ServiceProviderFederation#ChangingtheSAMLmetadataaboutSPFSPs

(only for developers with an account on the CLARIN IdP)

**Comment by andmor-** [comment]
This is fully covered by the latest improvements.

Changes:
1. The large `clarin-sp-metadata.xml` file was removed and split into one file per service provider inside the `metadata/` directory. This will enable service provider operators to manage their own metadata in a separate file.
2. Created a new [aggregated QA report page](https://clarin-eric.github.io/SPF-SPs-metadata/web/master_qa_report.html) featuring a filter input box for quickly finding SPs or issues.
3. The new aggregated QA report page now includes information about the last modification date, as well as the commit responsible for it (directly linking to github) to facilitate the matching between the metadata modifications and the QA report outcomes.
4. Introduced individual reports for each SP  containing all information above (but discarding unnecessary fields and features). The individual reports are accessible via the "entityID" links in the aggregated QA report and should provide SP operators with a more focused view on the QA assessment of their specific SP.
5. After a pull request is merged into `master` and the new QA reports are generated by the CI pipeline, a bot writes a comment on the pull request mentioning and linking the individual SP reports which changed due to this pull request. This clarifies the direct impact that the specific PR had on the QA assessment.
6. The `production` branch was removed and replaced by releases. From now on, the metadata changes will be propagated to our [feeds](https://infra.clarin.eu/aai/) as soon as a new release of the `master` branch is created by the repository operator.

To illustrate the functioning of the new system, see this example PR: https://github.com/clarin-eric/SPF-SPs-metadata/pull/188
